# bases:
#   - ../../../base/cloverfield-backend

# patches:
#   - replica_count.yaml

resources:
  - ../../../base/cloverfield-backend

patchesStrategicMerge:
  - replica_count.yaml  

namespace: clover-prd

images:
  - name: mellouliiahmed/cloverfield-backend
    newTag: "3c0fcce"